export const TOOGLE_DISPLAY_REGISTER = 'TOOGLE_DISPLAY_REGISTER';
export const SAVE_DATA_USER = 'SAVE_DATA_USER';
export const SAVE_ERROR_USER = 'SAVE_ERROR_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_LOGIN_FETCHING = 'SET_LOGIN_FETCHING';